# Generated by Django 4.2.18 on 2025-02-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='time started')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='time ended')),
                ('elapsed_time', models.IntegerField(default=None, null=True)),
                ('dist_from_average', models.CharField(max_length=50)),
                ('operation_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='timer.operationinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='timer.step')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='operationinstance',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.operationtype'),
        ),
        migrations.AddField(
            model_name='operationinstance',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.surgeon'),
        ),
    ]
