# Generated by Django 3.2.4 on 2025-01-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TimerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='time started')),
                ('end_time', models.TimeField(verbose_name='time ended')),
                ('detail', models.TextField(max_length=500)),
                ('elapsed_time', models.IntegerField(default=None, null=True)),
                ('dist_from_average', models.CharField(max_length=50)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.operationentry')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.surgeonentry')),
            ],
        ),
    ]
