# Generated by Django 4.2.18 on 2025-03-23 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField(max_length=500)),
                ('ocs1', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('elapsed_time', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='time started')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='time ended')),
                ('elapsed_time', models.IntegerField(default=None, null=True)),
                ('dist_from_average', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='surgeon',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), name='unique_case_insensitive_surgeon'),
        ),
        migrations.AddField(
            model_name='stepinstance',
            name='operation_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='timer.operationinstance'),
        ),
        migrations.AddField(
            model_name='stepinstance',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='timer.step'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_case_insensitive_step'),
        ),
        migrations.AddConstraint(
            model_name='operationtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('operation_type'), name='unique_case_insensitive_operation_type'),
        ),
        migrations.AddField(
            model_name='operationinstance',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.operationtype'),
        ),
        migrations.AddField(
            model_name='operationinstance',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.surgeon'),
        ),
    ]
